name: Gerador Anki Fluentli
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências necessárias
        run: |
          pip install -r requirements.txt

      - name: Executar a Auditoria e Geração do Anki
        run: python -u gerador_muti.py

      - name: Disponibilizar os Arquivos Prontos para Download
        uses: actions/upload-artifact@v4
        with:
          name: Fluentli-Decks-e-Cache
          path: |
            *.apkg
            cache_traducoes*.json